# Generated by Django 3.0.3 on 2020-08-02 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='createDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
